# Generated by Django 4.2.2 on 2023-06-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=10)),
                ('id_reserva', models.CharField(max_length=6, null=True)),
                ('nombres_cli', models.CharField(max_length=30)),
                ('apellidos_cli', models.CharField(max_length=30)),
                ('telefono_cli', models.CharField(max_length=30)),
                ('correo_cli', models.EmailField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_emp', models.CharField(max_length=10)),
                ('nombres_emp', models.CharField(max_length=30)),
                ('apellidos_emp', models.CharField(max_length=30)),
                ('direccion_emp', models.CharField(max_length=30)),
                ('sueldo_emp', models.CharField(max_length=7)),
                ('id_reserva', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vehiculo', models.CharField(max_length=4)),
                ('id_reserva', models.CharField(max_length=6, null=True)),
                ('patente_veh', models.CharField(max_length=6)),
                ('color_veh', models.CharField(max_length=10)),
                ('modelo_veh', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.CharField(max_length=6)),
                ('fecha', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vehiculo')),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
            ],
        ),
    ]
