# Generated by Django 4.2.2 on 2023-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('tipoarriendo', models.IntegerField(choices=[[0, 'Empresa ($100.000)'], [1, 'Normal ($130.000)']])),
                ('tipoveh', models.IntegerField(choices=[[0, 'Camioneta'], [1, 'Camión'], [2, 'Auto'], [3, 'Suv']])),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_cli',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
